### ISSUE TITLE
install on the system

### ISSUE THREAD

**Issue by AzizAK** [reactnativecn/react-native-custom-keyboard#3]
Hello,
can i install the custom keyboard to be used in every text input in the system? like Emoji?

**Comment by sunnylqm** [comment]
No. You can only use this in your app and in specific textinputs.

**Comment by AzizAK** [comment]
do you have any idea how to install keyboard in iOS ?

**Comment by oliversisson** [comment]
@sunnylqm actually, you can

https://customkeyboarddetails.blogspot.com/2019/02/using-react-native-in-android-custom.html

**Comment by JulioAugustoS** [comment]
Hello @oliversisson , would you have some example of how to use,I'm 3 months trying to make the custom keyboard for android and I'm not able to render a view made in react native within the keyboard area, I've been able to do this for ios but on android I have not yet succeeded, if you have any example and can share would be very show. Thank you.
