### ISSUE TITLE
[Android] select all bug

### ISSUE THREAD

**Issue by lipingruan** [reactnativecn/react-native-custom-keyboard#5]
select all will show system keyboard.

AndroidVersion: 6.0.2
RNVersion: 43.2

@tdzl2003

**Comment by lyxia** [comment]
同样的问题 
不很很好的隐藏android的系统键盘

**Comment by lyxia** [comment]
已解决：
对install的ReactEditText调用以下方法即可
/**
     * 隐藏系统键盘
     *
     * @param editText
     */
    public static void hideSystemSoftKeyboard(EditText editText) {
        int sdkInt = Build.VERSION.SDK_INT;
        if (sdkInt >= 11) {
            try {
                Class<EditText> cls = EditText.class;
                Method setShowSoftInputOnFocus;
                setShowSoftInputOnFocus = cls.getMethod("setShowSoftInputOnFocus", boolean.class);
                setShowSoftInputOnFocus.setAccessible(true);
                setShowSoftInputOnFocus.invoke(editText, false);
            } catch (SecurityException e) {
                e.printStackTrace();
            } catch (NoSuchMethodException e) {
                e.printStackTrace();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            editText.setInputType(InputType.TYPE_NULL);
        }
    }

**Comment by lipingruan** [comment]
@lyxia thank you.
@tdzl2003
