### ISSUE TITLE
[iOS] maxLength support

### ISSUE THREAD

**Issue by lipingruan** [reactnativecn/react-native-custom-keyboard#6]
insertText not support maxLength;

**Comment by lipingruan** [comment]
@tdzl2003

**Comment by singhlovey** [comment]
Hi @lipingruan 

Can you please provide me working example of custom keyboard in iOS app.  I am facing crashes whenever I am trying to open custom keyboard in iPhone.

Please Help!


I am getting crash "Thread 1: EXC_BREAKPOINT (code=1, subcode=0x102fc88c4)"
