### ISSUE TITLE
[iOS] Not Support RN 0.44.0

### ISSUE THREAD

**Issue by lipingruan** [reactnativecn/react-native-custom-keyboard#7]
hello,

@tdzl2003 , thank you for your plug-in, it's helpful for me.

I updated react-native to **0.44.0** (0.43.2 is normal), this plugin cannot visible on **iOS** platforms.

maybe you are long time offline, but I hope you can see this issues ;P

**Comment by JumalDB** [comment]
I have the same issue. Maybe someone know how to solve this?

**Comment by CoderZF** [comment]
@lipingruan is this problem solved? If not resolved, how do you customize the keyboard now?

**Comment by waterFallFlow** [comment]
react-native version: 0.44.3
I have changed the code and it worked:
![wechatimg1](https://user-images.githubusercontent.com/15437785/29016478-33d8166c-7b85-11e7-83ef-c230d690956f.jpeg)
use UITextField instead of UiTextView and init UITextField`s frame.
hope to be useful to you!

**Comment by lipingruan** [comment]
@waterFallFlow thank you.

**Comment by singhlovey** [comment]
@waterFallFlow 

I have changed UITextField to UiTextView but still I am getting an error shown below.


**Running application "CustomKeyboard" with appParams: {"rootTag":11,"initialProps":{"type":"hello","tag":267}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
2018-06-07 15:32:10.233 [fatal][tid:main] Exception '-[RCTTextField setInputView:]: unrecognized selector sent to instance 0x153d9da10' was thrown while invoking install on target CustomKeyboard with params (
    267,
    hello
)**

Please help!
